### ISSUE TITLE
How to check file types and reject when added

### ISSUE THREAD

**Issue by hfcorriez** [flowjs/flow.js#12]
RT.

**Comment by yanivkalfa** [comment]
This is an awful solution - not a solution really. more of a workaround.. and a bad user experience .. 
`The user select a file they thing is ok(because we dont limit the input) and then we cancel their selected .. `
cant be the best solution you can come up with.

@AidasK

**Comment by AidasK** [comment]
It's not a workaround, it's how it was created at that time

**Comment by yanivkalfa** [comment]
Please ignore my comment i just went over the code and saw you have an option to add "accept" through attributes object - which is what i was looking for.
