### ISSUE TITLE
Safari doesn't support directory uploads, but flow.supportDirectory is set true

### ISSUE THREAD

**Issue by lightman76** [flowjs/flow.js#124]
If I go to http://flowjs.github.io/ng-flow/ in Safari, I see the directory upload button, but you cannot actually choose a directory.  Dragging a directory shows a single file (the directory name) is uploaded.

It is documented in the flow readme that directory is Chrome only.  Looking at 
https://github.com/flowjs/flow.js/blob/master/src/flow.js#L60
it's testing for WebKit in the user agent.  

I'd propose that perhaps testing for /Chrome|Chromium/ instead - however I'm new to this project and HTML5 drag/drop in general, so not sure if there was a specific reason it was generalized to WebKit (for Android browsers or something).

If my proposed solution is acceptable and you'd prefer a pull request, just let me know.

**Comment by dshefchik** [comment]
This has been bothering me for awhile now, so I decided to go ahead and just do the pull request
