### ISSUE TITLE
what does "flow:r" mean in sample/Node.js/public/index.html

### ISSUE THREAD

**Issue by hxzqlh** [flowjs/flow.js#126]
When I read the `sample/Node.js/public/index.html` source , I found there are code block like this:

```
window.r = {
            pause: function () {
              r.pause();
              // Show resume, hide pause
              $('.flow-file-resume').show();
              $('.flow-file-pause').hide();
              $('.flow-progress .progress-resume-link').show();
              $('.flow-progress .progress-pause-link').hide();
            },
            cancel: function() {
              r.cancel();
              $('.flow-file').remove();
            },
            upload: function() {
              $('.flow-file-pause').show();
              $('.flow-file-resume').hide();
              r.resume();
            },
            flow: r
 };
```

I read the usage of Flow.js, but wondering the `flow:r` meaning? By the way, why did the `window.r` occur here, is it needed?

Thank you for your explaining!

**Comment by AidasK** [comment]
I think for debugging purposes, you can remove `flow: r`. Basically, this sample creates a public object with 3 methods. Methods are used in html native onclick handlers https://github.com/flowjs/flow.js/blob/master/samples/Node.js/public/index.html#L38
