### ISSUE TITLE
Misfire event 'complete' when resuming multiple files upload with first file had been completed

### ISSUE THREAD

**Issue by koolphp** [flowjs/flow.js#133]
When pausing and then resuming multiple files upload with the first file had been completed, flow will misfire event 'complete' in method flow.upload().

The reason is because flow.resume() resumes each file without checking if it has been completed.

Suggesting fix: change flow.resume() from:

each(this.files, function (file) {
          file.resume();
      });

to 

each(this.files, function (file) {
        if (! file.isComplete())
          file.resume();
      });

**Comment by manoswerts** [comment]
I have the same issue, but also with only 1 file that is not completed yet.

**Comment by evilaliv3** [comment]
is someone of you able to investigate this issue and provide a pull request?

we would like to have it fixed and it would be grewat if more user would join the effort!

**Comment by manoswerts** [comment]
I was mistaken, our code called the ´upload´ function instead of ´resume´. This caused the issue.

**Comment by evilaliv3** [comment]
thanks @manoswerts;

@KoolPHPSupport was this your issue also? can this ticket be closed?

**Comment by KoolPHPSupport** [comment]
No, it's still a problem with the current Flow.resume() method. In this method, all files are resumed without checking their status. Thus, even fully uploaded files are resumed, which will fired the 'complete' event another time.

I'm new to github. How should I make a pull request?

**Comment by jfcalvo** [comment]
Yes, same problem here.

**Comment by AidasK** [comment]
Feel free to make a pull request

**Comment by jfcalvo** [comment]
@AidasK please take a look to this https://github.com/flowjs/flow.js/pull/225

**Comment by AidasK** [comment]
Thanks @jfcalvo. Fix was merged
