### ISSUE TITLE
Implement cross-compatibility testing by means of SauceLabs

### ISSUE THREAD

**Issue by evilaliv3** [flowjs/flow.js#137]
While working on [GlobaLeaks](github.com/globaleaks/GlobaLeaks), we found out that It would be valuable to implement an integration with [SauceLabs](https://saucelabs.com/) in order to perform end-to-end testing in the cloud testing against cross-browser compatibility.

Given the fact that flow.js is using Grunt, this would be really simple by using [karma-sauce-launcher](https://github.com/karma-runner/karma-sauce-launcher)

This way the library would benefit of an output like the following: https://github.com/globaleaks/GlobaLeaks

[![Saucelabs Test Status](https://saucelabs.com/browser-matrix/globaleaks.svg)](https://saucelabs.com/u/globaleaks)

**Comment by evilaliv3** [comment]
Digging into the current flowjs codebase i've find out that flowjs is already under testing on saucelabs but currently only Chrome is tested.

I would suggest that we add at least:
- IE10, IE11, Edge
- Chrome (first compatible, latest version)
- Firefox (first compatible, latest version)
- Safari (first compatible, latest version)
- Iphone (first compatible, latest version)
- Android (first compatible, latest version)

Improvals:
1. The badge could be added to the ReadME.md
[![Saucelabs Test Status](https://saucelabs.com/browser-matrix/aidaskk.svg)](https://saucelabs.com/u/aidaskk)

2. the authorization token for saucelabs could be encrypted: http://docs.travis-ci.com/user/sauce-connect/

**Comment by AidasK** [comment]
Would be great, can you add it?

**Comment by evilaliv3** [comment]
sure! :)

**Comment by AidasK** [comment]
In case you haven't noticed, I have added you to flowjs group at github. You can access repository directly and add it without a pull request. Thanks for your effort!

**Comment by evilaliv3** [comment]
yeah yeah! i noticed! thank you so much and let's make this projects rocks! :)

**Comment by evilaliv3** [comment]
merged!
