### ISSUE TITLE
Test "should upload empty file" is failing on IE 10

### ISSUE THREAD

**Issue by evilaliv3** [flowjs/flow.js#147]
It seems that the test "should upload empty file" is failing on IE 10

This is visible from the output of travisCI run: https://travis-ci.org/flowjs/flow.js/builds/96726868

The obtained error is:
```
IE 10.0.0 (Windows 8 0.0.0) upload file should upload empty file FAILED
	Expected 0 to be 1.
	   at Anonymous function (/home/travis/build/flowjs/flow.js/test/uploadSpec.js:369:5)
	TypeError: Unable to get property 'progress' of undefined or null reference
	   at Anonymous function (/home/travis/build/flowjs/flow.js/test/uploadSpec.js:370:5)
```

Given the following code of the test the reason seems to lie in the call "new Blob([])" 
that probably is not returning a Blob object on IE10
```
  it('should upload empty file', function () {
    var error = jasmine.createSpy('error');
    var success = jasmine.createSpy('success');
    flow.on('fileError', error);
    flow.on('fileSuccess', success);

    flow.addFile(new Blob([]));
    var file = flow.files[0];
    flow.upload();
    expect(requests.length).toBe(1);
    expect(file.progress()).toBe(0);
    requests[0].respond(200);
    expect(requests.length).toBe(1);
    expect(error).not.toHaveBeenCalled();
    expect(success).toHaveBeenCalled();
    expect(file.progress()).toBe(1);
    expect(file.isUploading()).toBe(false);
    expect(file.isComplete()).toBe(true);
  });
```

**Comment by AidasK** [comment]
https://connect.microsoft.com/IE/feedback/details/813443/uploading-empty-file-ie10-ie11-hangs-indefinitely
Might be the case. I have experienced this bug by myself. The only fix for this is to restrict empty file upload for IE browsers(but this is not a solution, because users might need to upload empty files as well).

**Comment by AidasK** [comment]
Can we ignore this test case for IE?

**Comment by evilaliv3** [comment]
exactly! i just found that this was the cause before looking at your comment!

i'm goind to test the removal of that patch in a branch just to understand what happens if i do that and see if i'm able to fix it.

**Comment by evilaliv3** [comment]
![screenshot from 2015-12-14 15 54 20](https://cloud.githubusercontent.com/assets/217034/11784121/ff580b0c-a27a-11e5-8d46-5862215cc25b.png)

@AidasK: i'm wondering if that was simply related to base test where you were using IE in compatible mode and maybe you were mixing messy IE behaviours.
what about trying to go for a revert and get eventually user feedback? 

we have anyhow in place the unittests so that we can monitoor if it is happening again or not.

**Comment by AidasK** [comment]
https://github.com/flowjs/flow.js/blob/master/src/flow.js#L585
`(!ie10plus || ie10plus && file.size > 0)`
Are you talking about this line? I think we can change it for ie10 browsers only, because it is going to be fixed in the edge version in a year or two.

**Comment by evilaliv3** [comment]
exactly; i've already removed it and you can see that it is working.

i would suggest to merge this revert https://github.com/flowjs/flow.js/commit/562cdf9f8d9577b50fe0365ba65224d1fec17315 and eventually manage to really solve it if it would rehappen.

**Comment by AidasK** [comment]
Don't know if it is possible to solve this. If this fix requires loads of effort, then you can revert it.

**Comment by evilaliv3** [comment]
Ok the test is now conditional an we also verify that the exception condition for IE10 is used only of what we think is IE10.
