### ISSUE TITLE
Publish the package in the npm registry

### ISSUE THREAD

**Issue by Undergrounder** [flowjs/flow.js#148]
I wan't to use this package with webpack, but there is no published version of the package in npm.

There is another problem: The npm package name flow.js is already registered.

For publishing in npm registry two steps are necessary:
  - Change the name in package.json to any unused name. Maybe flowjs?
  - Publish it to the registry. Should be done by some mantainer, if not I could.

Any better idea?

**Comment by evilaliv3** [comment]
@AidasK any idea? probably we can only use flowjs as naming there; i'm immediatly going to register it.

in addition i will try to contact the maintainer of https://www.npmjs.com/package/ng-flow in order to move it under the official control.

**Comment by evilaliv3** [comment]
ah no great the ng-flow is already pointing to us.

**Comment by evilaliv3** [comment]
arg, it seems that all are already taken: flow, flow.js, flow_js, flow-js

o_o

**Comment by Undergrounder** [comment]
Yes, I was going to post it now.... alternative names?

**Comment by AidasK** [comment]
Maybe `flowjs/flow.js`?  I don't think it matters as long we mention this name in documentation

**Comment by Undergrounder** [comment]
The suffix .js should't be used: https://docs.npmjs.com/files/package.json

Maybe the name with a scope? Are there any known problems with webpack/systemjs?

Suggestion if no bug found: @flowjs/flowjs

**Comment by evilaliv3** [comment]
@Undergrounder they suggest it int the general but the library since a lot is called that way :)

francly i'm think about moving all to the @flowj namescope
@flowjs/flow.js
@flowjs/ng-flow
@flowjs/fusty-flow

@AidasK what do you think? this way we can more properly be "official" maintainers.

**Comment by evilaliv3** [comment]
https://www.npmjs.com/package/@flowjs/flow.js

**Comment by AidasK** [comment]
:+1: Cool, looks good for me!

**Comment by evilaliv3** [comment]
by the way there is no signing process so when the package is published anyhow it is published. do you suggest to apply the scope to other packages anyhow?

**Comment by commandtab** [comment]
Excellent! Thanks for publishing on npm!

Now I can avoid doing:

```js
"dependencies": {
  "flowjs": "git+https://github.com/flowjs/flow.js.git#v2.9.0"
}
```

**Comment by Undergrounder** [comment]
I have now testet it. All working correctly.

Thanks for your great work!

**Comment by AidasK** [comment]
@evilaliv3 Have you tried installing npm packages after renaming? Or my npm version is too old?

```
~/Projects/flow.js (master) $ npm install
npm ERR! install Couldn't read dependencies
npm ERR! Error: Invalid name: "@flowjs/flow.js"
npm ERR!     at ensureValidName (/usr/lib/nodejs/normalize-package-data/lib/fixer.js:284:15)
npm ERR!     at Object.module.exports.fixNameField (/usr/lib/nodejs/normalize-package-data/lib/fixer.js:199:5)
npm ERR!     at /usr/lib/nodejs/normalize-package-data/lib/normalize.js:29:38
npm ERR!     at Array.forEach (native)
npm ERR!     at normalize (/usr/lib/nodejs/normalize-package-data/lib/normalize.js:28:15)
npm ERR!     at final (/usr/lib/nodejs/read-package-json/read-json.js:342:33)
npm ERR!     at then (/usr/lib/nodejs/read-package-json/read-json.js:126:33)
npm ERR!     at /usr/lib/nodejs/read-package-json/read-json.js:331:40
npm ERR!     at evalmachine.<anonymous>:268:14
npm ERR!     at /usr/lib/nodejs/graceful-fs/graceful-fs.js:102:5
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 3.19.0-43-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /home/aidas/Projects/flow.js
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.4.21
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /home/aidas/Projects/flow.js/npm-debug.log
npm ERR! not ok code 0
```

**Comment by evilaliv3** [comment]
Yep i do not get any issue:

```bash
evilaliv3@remotehost:~/Devel/flow.js$ npm install -d
npm info it worked if it ends with ok
npm info using npm@2.14.7
npm info using node@v4.2.3
npm info preinstall @flowjs/flow.js@2.9.0
npm info package.json grunt@0.4.5 No license field.
npm info package.json grunt-contrib-concat@0.5.1 No license field.
npm info package.json grunt-karma-coveralls@2.5.4 No license field.
npm info package.json grunt-template@0.2.3 No license field.
npm info package.json sinon@1.7.3 No license field.
npm info build /home/evilaliv3/Devel/flow.js
npm info linkStuff @flowjs/flow.js@2.9.0
npm info build /home/evilaliv3/Devel/flow.js/node_modules/jasmine-core
npm info preinstall jasmine-core@2.4.1
npm info linkStuff jasmine-core@2.4.1
npm info install jasmine-core@2.4.1
npm info postinstall jasmine-core@2.4.1
npm info install @flowjs/flow.js@2.9.0
npm info postinstall @flowjs/flow.js@2.9.0
npm info prepublish @flowjs/flow.js@2.9.0
npm info ok 
```

my version of node is the 2.14.7 

```bash
evilaliv3@remotehost:~/Devel/flow.js$ npm -v
2.14.7
```

**Comment by evilaliv3** [comment]
Bam! https://www.npmjs.com/~flowjs
