### ISSUE TITLE
npm registry v2.9.0 isn't the 2.9.0 release.

### ISSUE THREAD

**Issue by Undergrounder** [flowjs/flow.js#151]
I'm getting the last master commit when checking out the 2.9.0 release in npm. I have noticed this, because the 2.9.0 code works well with my actual code, but the current master release doesn't.

The 2.9.0 release should be removed from npm.

Solution:
 - Maybe a 2.9.1 release that is the 2.9.0 version + the package.json name change?

**Comment by evilaliv3** [comment]
Right @Undergrounder !

@AidasK i was about to release a package and i've encountered few issues in the package.json devDependencies not including all the dependencies needed for "grunt build".  I'm going to fix it and try to do a release at this time.

Let me know if you prefer to go for a 3.0, but i think it would be ok to have still a 2.9.1 and iterate on stabilization and then do a 3.0 on the new year!

**Comment by evilaliv3** [comment]
ah, @AidasK, i see that you already sketched  a [3.0](https://github.com/flowjs/flow.js/issues?q=is%3Aopen+is%3Aissue+milestone%3Av3]) milestone in past.

what are you considering as priorities for it?

**Comment by evilaliv3** [comment]
Bam! https://www.npmjs.com/~flowjs
