### ISSUE TITLE
New releases not published to npm

### ISSUE THREAD

**Issue by Undergrounder** [flowjs/flow.js#157]
The releases 2.10.0 and 2.10.1 are not in the npm registry:

https://www.npmjs.com/package/@flowjs/flow.js

**Comment by evilaliv3** [comment]
Done! thank you undergrunder for notifying it!

@AidasK i've still to grant you permissions on npmjs, let me know on whch mai i should generally enable you on this kind of things ;)

to publish the package generally after the release we should run ```npm publish```

**Comment by evilaliv3** [comment]
Bam! https://www.npmjs.com/~flowjs
