### ISSUE TITLE
How about a fileRemoved event?

### ISSUE THREAD

**Issue by SuberFu** [flowjs/flow.js#164]
For use cases where we want to display the list of files currently in the list to be uploaded, having a fileRemoved event could centralize all the list update function (trigger the list update on filesSubmitted and fileRemoved event).

I got that functionality by adding "this.fire('fileRemoved', file);" to removeFile function.

P.S. If I want to contribute, which one do I actually contribute on (master? develop?)? I clicked on the "View our development branch" and the last commit was a year ago.

**Comment by evilaliv3** [comment]
it think it's ok to have a file removed event or you can simply filter them not showing it. i've to think a little bit to what could be the benefits.

if you want to contribut you are right the master branch is the one to be kept as reference and probably the develop one does not contain anything of value.

**Comment by SuberFu** [comment]
In my case, I have a single UI list that displays the list of uploaded files and their state, plus interface "buttons" that allows start/resume, pause, cancel the files upload. In addition, there are potential external events that could cause files to the removed.
Now, I could have it as part of the wrapper around flow.js, but I want to add to the library for several reasons.
1. API symmetry: There's an event for when files are added to upload queue, but no equivalent event for when a file is removed from upload queue (off-side, perhaps a "fileRemoving" to allow user to cancel a file removal? Although that's a case I can't think of any use for).
2. Cleaner user code: Users of flow.js may have several external states that depends on the upload-queue of flow.js. Instead of having a wrapper code that specifically target all cases where a file could be removed (for example, invoking cancel() on individual FlowFile, invoking cancel() on Flow, adding file in singleFile mode), an event allow user to catch all instance of when a file leaves the upload queue.
3. I like this library, and I want to contribute.

I've a pull request created for this. #165

**Comment by SuberFu** [comment]
Pull request resubmitted with rebase #167

**Comment by SuberFu** [comment]
Issue resolved by #167 pull.
