### ISSUE TITLE
fileRemoved does not exists in dist flow.js

### ISSUE THREAD

**Issue by hinablue** [flowjs/flow.js#168]
fileRemoved in src is working fine, dist does not. I used the ng-flow and found the flow.js dist is too old ( Cause the bower always use the dist file.)

**Comment by SuberFu** [comment]
That change was pretty recent, so unless there was a release, the one in dist will not work.

**Comment by commandtab** [comment]
Related: How often do new releases get made?
(I'm interested in taking advantage of `fileRemoved` too :smile:)

**Comment by evilaliv3** [comment]
you are all right!

@AidasK what do you say? would you like to review what integrated so far and releae a new one?

**Comment by AidasK** [comment]
Hi, thanks for your contribution! I won't be available for a couple of
weeks, feel free to make a patch release. There is a grunt command for this

**Comment by evilaliv3** [comment]
k!

**Comment by evilaliv3** [comment]
@AidasK i think that it would be great to:

- integrate https://github.com/flowjs/flow.js/issues/171
- proceed with updating dist and release both on npm/bower

do you have by the chance time for doing this?

**Comment by evilaliv3** [comment]
@AidasK this could be closed right?

We should then export the event on ng-flow: https://github.com/flowjs/ng-flow/issues/284
@AidasK could you provide some guidelines to @alexgoldstone so that he can eventually start preparing the pull request?
