### ISSUE TITLE
filesSubmitted fires even if user return false to filesAdded event.

### ISSUE THREAD

**Issue by SuberFu** [flowjs/flow.js#175]
Currently, if a user supplied handler for filesAdded return 'false', the files won't be added to the FlowJS. However, the filesSubmitted event still fires with all the files passed to filesAdded.
Is this an intended behavior?

**Comment by evilaliv3** [comment]
@AidasK ?

**Comment by AidasK** [comment]
Yep, this is a bug. 
https://github.com/flowjs/flow.js/blob/master/src/flow.js#L597
`filesSubmitted` should be in the `if` statement above
