### ISSUE TITLE
Consider making `generateUniqueIdentifier` async

### ISSUE THREAD

**Issue by oh-wo** [flowjs/flow.js#183]
Hi all,

Just wondering if there has ever been any talk of making the `generateUniqueIdentifier ` function return a promise, rather than immediately. This would be useful in the case where file ids are generated server side and a http response is needed. Alternatively it could be modified to pass a completion callback, similar to the `preprocess` function which passes `preprocessFinished`.

If there is another way to achieve the same result without modifying `generateUniqueIdentifier` please share as I am interested.

**Comment by AidasK** [comment]
I think you should add the file to the queue only then you have an id. There is `addFile` function for that.

**Comment by oh-wo** [comment]
Ah! Thanks very much Aidas. Are you suggesting observing `upload click` / `upload drop` events manually, getting an id and then once all that's done calling `addFile`? 

(Apologies for the late reply!)

**Comment by mancioshell** [comment]
I think this should be considered as a really useful feature.
