### ISSUE TITLE
Incorrect union ambiguity with object spread operator

### ISSUE THREAD

**Issue by robz** [flowjs/flow.js#190]
Suppose I have a type like this: 
```
type T = 
  {kind: 'a', x: number} |
  {kind: 'b', x: number};
```
And suppose values of this type are constructed in a function like this:
```
function f1(input: T): T {
  return {...input, kind: 'a'};
}
```
Then flow throws an error:
```
return {...input, kind: 'a'};
       ^ object literal. Could not decide which case to select
function f1(input: {x: number}): T {
                                 ^ union type 
```
However, if the spread occurs after the `kind` key , then flow does not throw an error:
```
function f2(input: T): T {
  return {kind: 'a', ...input};
}
```
I think both of these are bugs, based on how object spreading works (properties defined later override ones defined earlier). In `f1`, `kind: 'a'` overrides the value of `input.kind`, so there should be no ambiguity. In `f2`, `input.kind` overrides `kind: 'a'`, making the resulting type dependent on `input.kind`, which is ambiguous.   

https://flowtype.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgAqYAvGKmGAN4DWAlgHYAmAXGAOQCG7ANGAB5sGAVwC2AIzwAnAL5gAPhWr1mbduN4ChYybIDcS1FGEMAxhjpwGYKAEYAFIxzCMbQgEo31JVLwZhUtZUAHShTi58Kqwc3DIGMujGZhZWNgBMjgzOrkSeRN6Uvv6ByozRXJqhweEYcagyQA

**Comment by evilaliv3** [comment]
@robz i think you opened the ticket on the wrong repository :)

the right one for your "flow" library is: https://github.com/facebook/flow
