### ISSUE TITLE
Can't seem to resolve required module for .vue file

### ISSUE THREAD

**Issue by Gacnt** [flowjs/flow.js#198]
Using the latest version of flow, with eslint in Atom text editor I get

`./views/Home/Home.vue: Required module not found.`
```
// @flow

import Vue from 'vue/dist/vue.js';
import VueRouter from 'vue-router';
> import Home from './views/Home/Home.vue'; -- Error eslint/flow
```

My Flow Config

```
[ignore]
.*/node_modules/fbjs/.*
.*/git/.*

[include]

[libs]

[options]
```

I've tried adding  things like `.*/app/.*` to include but it doesn't seem to resolve

This is my folder structure

![Image of Folder Structure](http://i.imgur.com/2Z2b4f6.png)

**Comment by nobilix** [comment]
the same here

**Comment by nobilix** [comment]
the solution

1. add to the .flowconfig
```
[options]
module.name_mapper.extension='vue' -> '<PROJECT_ROOT>/flow/EmptyModule.js.flow'
```

2. add this file to your project
`/flow/EmptyModule.js.flow`
with the content:
```
// @flow

declare export default {}

```

**Comment by AidasK** [comment]
wrong repo
