### ISSUE TITLE
Object.values() type appears to be an Array<mixed> even when it is inferable.

### ISSUE THREAD

**Issue by drarmstr** [flowjs/flow.js#205]
I would like to iterate the values of an object using `Object.values()`, however the return type appears to always be `Array<mixed>`.  If the type of the object is as follows:

    type Foo = { [key: string]: Bar };

Then the type should be inferable:

    for (const bar of Object.values(foo)) {
        // bar can be typed as Bar here instead of mixed
    }

**Comment by vijayaggarwal** [comment]
+1

**Comment by AidasK** [comment]
wrong repo
