### ISSUE TITLE
Question: Will flow.js work against the AWS S3 API?

### ISSUE THREAD

**Issue by jpillora** [flowjs/flow.js#22]
Will flow.js work against the AWS S3 API? I.e. resumable uploads etc

I'm looking into building a client-side only S3 file browser/uploader/editor

https://github.com/jpillora/xdomain
https://github.com/jpillora/s3hook
https://github.com/jpillora/cms4

**Comment by r-shah** [comment]
Since this looks like very old issue, just wanted to check if current library supports file upload to amazon s3?
I don't get it working while setting AWS s3 presigned url to $flow.opts.target. Please advise.
