### ISSUE TITLE
Question: "Special" strings?

### ISSUE THREAD

**Issue by suchipi** [flowjs/flow.js#221]
I have several types in my codebase which represent strings with special meaning; they're used to document the response from our server API. They're all just aliases for string; they look like this:
```js
// String that can be shown directly to the user
type HumanReadableString = string;

// Represents an ISO8601 datetime string
type DateString = string;
```

While useful for documentation, currently flow treats them no differently than normal strings. Is it possible to make flow consider these "more specific" than strings? That is, my desired functionality is:
```js
function parseDate(dateString: DateString): Date { /* ... */ }
const someDateString: DateString = "2017-05-18T14:02:04+00:00";
const notADateString = "foo";

parseDate(someDateString);
// $ExpectError
parseDate(notADateString);
```

"More specific strings" could also be useful in these situations:
* String that is escaped and safe to insert into html
* Template string (handlebars or etc)
* String that has been URI-escaped
* JSON string that will be a certain shape when parsed (`const str: JSONString<{ foo: string }> = "{\"foo\":\"bar\"}"`)

**Comment by AidasK** [comment]
Is this issue meant for flow.js file uploader?

**Comment by suchipi** [comment]
Nope; sorry!
