### ISSUE TITLE
Get http code with fileError

### ISSUE THREAD

**Issue by johaven** [flowjs/flow.js#233]
Is there a way to retrieve http code on error ?

I use flowjs with Angular(4), i need to know when my token has expired (http code: 401).
In my Angular services i have an auto refresh for this case, but flowjs requests working in parallel (because no Angular module or integration at this time).
For the moment i grep on error message but it is a low check, an error code is cleaner.

**Comment by AidasK** [comment]
You can get response status by accessing xhr object `chunk.xhr.status`. Chunk is available on every http response method.

**Comment by johaven** [comment]
Thank you 👍

**Comment by pavankumarkatakam** [comment]
Hi @johaven, could you give me an example of how you are using the Flow js in Angular 4.

**Comment by johaven** [comment]
@pavankumarkatakam here :)

```javascript
import {Injectable} from '@angular/core'
import * as Flow from '@flowjs/flow.js'

@Injectable()
export class FilesService {
    public flowUpload: any
    private maxRetries = 5
    private nbRetries = 0
    private folders = {}

    constructor(private myService: MyService) {
        this.flowUpload = new Flow({
            headers: () => this.myService.auth.getCSRFHeader(),
            target: `${this.myService.uploadAPI}`,
            allowDuplicateUploads: false,
            chunkRetryInterval: 1000,
            maxChunkRetries: 3,
            simultaneousUploads: 1
        })
        this.initEvents()
    }

    initEvents() {
        this.flowUpload.on('fileRetry', () => {
            this.onFileRetry()
        })

        this.flowUpload.on('filesSubmitted', files => {
            this.onNewFiles(files)
        })

        this.flowUpload.on('complete', () => {
            this.onComplete()
        })
    }
...
```

**Comment by pavankumarkatakam** [comment]
Thank you @johaven , Actually, Im looking for how to get the Element reference, it will not work with regular `document.getElementId` because the HTML is dynamically adding to the DOM, after searching I got that there is a decorator called `@ViewChild` in angular 4.

**Comment by johaven** [comment]
@pavankumarkatakam  It's depending of your code, i use for example a dropdown to load files, i call a function when showing my dropdown like this:
```javascript
<div *ngIf="condition" class="btn-group btn-group-sm mr-1" (onShown)='initUpload()' dropdown>
    <button dropdownToggle type="button" placement="bottom" class="btn btn-sm btn-secondary dropdown-toggle">
      <i class="fa fa-plus"></i></button>
    <ul *dropdownMenu class="dropdown-menu" role="menu">
     <li role="menuitem">
        <a class="dropdown-item" id="uploadFilesButton"><span translate><i class="fa fa-desktop mr-2"></i>Upload files</span></a>
     </li>
    </ul>
  </div>
```

In component:
```javascript
initUpload() {
if (!this.uploadButtonsShowed) {
    this.uploadButtonsShowed = true
    this.flowUpload.assignBrowse(document.getElementById('uploadFilesButton'))
}
```

**Comment by pavankumarkatakam** [comment]
Ok Thanks fo rmuch info.

**Comment by johaven** [comment]
`chunk.xhr.status` return always 0 now.

Can you explain why ?

**Comment by AidasK** [comment]
have you updated package version?

**Comment by johaven** [comment]
It happens when no web server is used (like nginx), on standalone mode (with uwsgi / flask).
