### ISSUE TITLE
There is no event before each file send?

### ISSUE THREAD

**Issue by dkavelin** [flowjs/flow.js#242]
All I find is opts.preprocess but no flow.Events

**Comment by aayusharyan** [comment]
You can use the event of `progress` to check for Events of Chunk. That is called whenever a new Chunk is started or a new chunk is finished uploading.

**Comment by aayusharyan** [comment]
And if you want to check for the file, then you can check the `uploadStart` event.

**Comment by aayusharyan** [comment]
@AidasK 
It's an old issue and can be resolved using the functions. I would suggest closing this...
