### ISSUE TITLE
add simultaneousUploadsPerFile Option

### ISSUE THREAD

**Issue by Vringe** [flowjs/flow.js#263]
I'd like to have a `simultaneousUploadsPerFile` option so you can have multiple chunks uploaded at the same time but only for one file at a time. Chunks of the next files should wait until every chunk of the first file is uploaded.

Reason for this is that I sometimes get duplicate folders (database) created on the server side.

Is there any workaround for this?

**Comment by FabianElsmer** [comment]
Your database operations should always check if they are even necessary, only create a folder if the folder does not already exist?

**Comment by AidasK** [comment]
You should use database transactions
