### ISSUE TITLE
Change params names

### ISSUE THREAD

**Issue by akididou** [flowjs/flow.js#270]
Why did you remove the capacity to change params names ? 

On ResumableJS we can use : 

> chunkNumberParameterName The name of the chunk index (base-1) in the current upload POST parameter to use for the file chunk (Default: resumableChunkNumber)
totalChunksParameterName The name of the total number of chunks POST parameter to use for the file chunk (Default: resumableTotalChunks)
chunkSizeParameterName The name of the general chunk size POST parameter to use for the file chunk (Default: resumableChunkSize)
totalSizeParameterName The name of the total file size number POST parameter to use for the file chunk (Default: resumableTotalSize)
identifierParameterName The name of the unique identifier POST parameter to use for the file chunk (Default: resumableIdentifier)
fileNameParameterName The name of the original file name POST parameter to use for the file chunk (Default: resumableFilename)
relativePathParameterName The name of the file's relative path POST parameter to use for the file chunk (Default: resumableRelativePath)
currentChunkSizeParameterName The name of the current chunk size POST parameter to use for the file chunk (Default: resumableCurrentChunkSize)

So i use this function to change them : 

`import { FlowChunk } from '@flowjs/flow.js';`

   ```
 FlowChunk.prototype.getParams = function() {
      return {
        chunk_number: this.offset + 1,
        chunk_size: this.flowObj.opts.chunkSize,
        current_chunk_size : this.endByte - this.startByte,
        total_size: this.fileObj.size,
        identifier: this.fileObj.uniqueIdentifier,
        file_name: this.fileObj.name,
        relative_path: this.fileObj.relativePath,
        total_chunks : this.fileObj.chunks.length
      };
    },
```

Maybe you can re-add the capacity to change params names ? 
Peace

**Comment by AidasK** [comment]
It was removed, because it's not flexible enough. You can use `query` config as a callback to rename or edit any parameter also

**Comment by lmiguelmh** [comment]
Thank you for this library.
In my case I needed to upload a single file to S3.
I make it work by using a single request (not multipart) and by removing the additional headers:

```
options: {
  ...
  chunkSize: 5 * 1024 * 1024 * 1024,  // don't split the file, also S3 has a 5GB limit
  query: function (file, chunk, isTest) {
    chunk.getParams = (a) => ({})  // overwriting function that return params (flowChunkNumber, ...)
  },
}
```
