### ISSUE TITLE
Inconsistancy between old version, code and documentation regarding successStatuses

### ISSUE THREAD

**Issue by JBerggren** [flowjs/flow.js#275]
https://github.com/flowjs/flow.js/commit/3ae086d101575d082b1736b262fc410a2b55e237 changed the list of successStatuses to also include 204. This is a breaking change for services which have used 204 for indicating that there is literaly "no content" for the request to check if the chunk already exists on the server. Suggest that this is reverted OR that the documentation is updated since the code (in src/flow.js) is now doing one thing and the documentation and dist-version (/dist/flow.js) is doing another (https://github.com/flowjs/flow.js/search?q=successStatuses&unscoped_q=successStatuses).

**Comment by AidasK** [comment]
Lets revert it since it wasn't released yet. Stability of the library matters more to me than debatable features

**Comment by AidasK** [comment]
https://github.com/flowjs/flow.js/commit/6ecaee4d248dc71ed43110b6e7343913cc2943ef
