### ISSUE TITLE
Creating a new Release

### ISSUE THREAD

**Issue by aayusharyan** [flowjs/flow.js#280]
@AidasK 
Should we create a new Release of this?
If so, then how do you do it and what will be the version number?

Thanks.

**Comment by AidasK** [comment]
I have a grunt command for this. My flow is:
```
git pull
npm install
grunt release:patch
```
https://github.com/flowjs/flow.js/blob/master/Gruntfile.js#L117

And that is it. Minified file is created and pushed, tagged automatically. If you want, feel free to do it or I will do it on the weekend

**Comment by aayusharyan** [comment]
Have you tried https://github.com/flowjs/flow.js/packages ?

**Comment by AidasK** [comment]
If you are asking if this package is published in npm, then yes. But I have
never tried github packages. Would you like to set it up?

**Comment by aayusharyan** [comment]
I'll try this over the weekend.
Right now I am working on Making this Library plug-n-play for S3 Uploads. 😅

**Comment by AidasK** [comment]
Sounds super cool :))

**Comment by AidasK** [comment]
Published and released 2.14.0

**Comment by aayusharyan** [comment]
Thanks man. :)
I'll close this now.
