### ISSUE TITLE
The npm version 2.13.2 and ".dist" folder don't have `changeRawDataBeforeSend` option

### ISSUE THREAD

**Issue by JonUK** [flowjs/flow.js#282]
When importing the npm package `@flowjs/flow.js@2.13.2`, the code appears to be out of date with the GitHub repo and does not contain code to handle the `changeRawDataBeforeSend` option.

Also, in the GitHub repo, the `dist` folder version doesn't contain code to the the  `changeRawDataBeforeSend` option either.

**Comment by AidasK** [comment]
published and released
