### ISSUE TITLE
MD5 checksum for each Chunk

### ISSUE THREAD

**Issue by honzahana** [flowjs/flow.js#286]
Is it possible to add a MD5 checksum calculation for each `Chunk`?

I would like to add calculation to [`headers` config](https://github.com/flowjs/flow.js#configuration) (as function), but the reading `Blob` works on the `Promise` principle. So I can't suspend `headers` function until `Promise` is done.

**Comment by AidasK** [comment]
You can definitely can do it, though I can't find a proper example for it. Issue is called https://github.com/flowjs/flow.js/issues/42

**Comment by honzahana** [comment]
I found an example: https://github.com/flowjs/flow.js/issues/9#issuecomment-288750191
