### ISSUE TITLE
Object.entries always returns type [ string, mixed ]

### ISSUE THREAD

**Issue by lawlietmester** [flowjs/flow.js#320]
Object.entries always returns type [ string, mixed ].

But for example once I have 

```
var start: { [ string ]: string } = { 'a': 'one', 'b': 'two', 'c': 'three' };
var end: Array<[ string, string ]> = Object.entries( start ); 
// ^ Flow thinks this is Array<[ string, mixed ]>
```

This will throw the error about mixed as 2nd element in array.

Tested on version `0.135`

**Comment by drzraf** [comment]
There is no occurrence of `Object.entries` in the code, nor version `0.135`.

**Comment by lawlietmester** [comment]
@drzraf What repository contains basic definitions for internal browser functions like Array.reduce, Object.assign, etc.?
