### ISSUE TITLE
Drag and Drop - Restrict deleting the email dragged from outlook

### ISSUE THREAD

**Issue by MaximRobota** [flowjs/flow.js#323]
STR: 

Go to outlook client
Drag and drop email  from outlook into Documents
Email is deleted in outlook.
This is apparently a issue in chrome. Please see the below solution options to the issue. 
https://bugs.chromium.org/p/chromium/issues/detail?id=322605
Solution:
https://answers.microsoft.com/en-us/msoffice/forum/all/drag-and-drop-works-however-deletes-email-can-we/865f60c3-7980-4465-8a19-4d60b0ae5aba?rtAction=1575537469456&page=2

Please apply the solution, thanks.

**Comment by AidasK** [comment]
Not flow.js related

**Comment by MaximRobota** [comment]
Needs to modify events here: https://github.com/flowjs/flow.js/blob/e83d2d9d72d0b4f96f34b508fd7d734f36075be2/src/flow.js#L439-L440
