### ISSUE TITLE
When importing a folder, all files from same folder have same relativePath [v3 only]

### ISSUE THREAD

**Issue by bertrandg** [flowjs/flow.js#341]
I got this bug when importing a folder using function `webkitReadDataTransfer()` (& `readDirectory()`).

**Here are the details, I drop the following `all` folder:**

![image](https://user-images.githubusercontent.com/7031941/119537892-cf8a0e80-bd8a-11eb-9215-c1bd441c726a.png)

**Then, like you see in screenshot, all files inside a folder got same `fullPath` property:**

![image](https://user-images.githubusercontent.com/7031941/119538083-08c27e80-bd8b-11eb-9718-70cffc7d5661.png)
![image](https://user-images.githubusercontent.com/7031941/119538220-2e4f8800-bd8b-11eb-8b85-f5eb19145767.png)
![image](https://user-images.githubusercontent.com/7031941/119538275-3c9da400-bd8b-11eb-8295-4c155d74a266.png)
![image](https://user-images.githubusercontent.com/7031941/119538422-63f47100-bd8b-11eb-89e5-2ee036dd8746.png)

I found the error comes from there:

https://github.com/flowjs/flow.js/blob/218b2bf76d840a4eb0013e3db2a0ff764d93eab7/src/Flow.js#L257

That could be easily fix, I will make a merge request later this week if you are ok with it.

**Comment by AidasK** [comment]
yes, feel free to submit it. Have you checked v2? Does it handle it ok?

**Comment by bertrandg** [comment]
Fix merged for v3.

And v2 handles it ok:
![image](https://user-images.githubusercontent.com/7031941/120183470-068b7480-c210-11eb-98a2-77edda4e8cd5.png)

**Comment by AidasK** [comment]
That's great! Thanks for double checking it
