### ISSUE TITLE
Question: Is it possible to avoid long relative paths ?

### ISSUE THREAD

**Issue by searleser97** [flowjs/flow.js#345]
Could you point me on an example of how to configure `flow.js` so that I could just use the name of a file for imports instead of long relative paths ?. This implies that the name of my files in my entire working directory are **unique**.

example:

Directories
```
pages/components/foo.js
common/types/abc.js
```

Current import statements

```ts
import foo from "../../pages/components/foo"
import abc from "../common/types/abc"
```

Desired import statements
```ts
import foo from "foo"
import abc from "abc"
```

**Comment by drzraf** [comment]
I guess this refers to https://github.com/facebook/flow
