### ISSUE TITLE
v3 does not support pausing/resuming from stream

### ISSUE THREAD

**Issue by drzraf** [flowjs/flow.js#346]
The current `pause` process consist into aborting all ongoing XHR object. Conversely `resume` call `Flow.upload()` again which goes over each pending chunk.

In the case of ReadableStream we can not expect to `read()` twice a regular file (as expected by `FlowChunk.send()`).
A possible implementation could conserve the XHR payload in order to recreate it again (instead of setting `FlowChunk`'s XHR to `null`)

**Comment by drzraf** [comment]
I've a problem with the current code paths.

If I call `await files[0].chunks[0].send();` (uploading only one chunk of one file), it'll call `FlowChunk.doneHandler()` which in turn calls parent's `flowObj.uploadNextChunk()` which read/consume/send all remaining chunks.
It's a counter-intuitive design. Wouldn't we prefer a more predictable chaining process?

**Comment by AidasK** [comment]
I think you have mentioned this problem earlier. I agree that it can be improved

**Comment by drzraf** [comment]
#348 fixed it. Pause & resuming from stream now works.
The counter-intuitive `pause()/resume()` design can be solved in a subsequent issue.
