### ISSUE TITLE
General discussion

### ISSUE THREAD

**Issue by vvllaadd** [flowjs/flow.js#4]
Hi,

Well done with the library! Although it currently doesn't seem to be much difference between this and resumablejs, I prefer flow's code structure.
Unfortunately it inherits the same big performance issue.
The "testChunks" idea is nice, but it is useless in its current form. If let's say one have uploaded 5/10 chunks in a previous session and wishes to resume the transfer, wouldn't be more practical for Flow to send only ONE single GET requests to retrieve the size of what has been already uploaded to the server and continue from there, instead of testing all chunks from 1 to 10?
There are a couple of more big problems, but let's start with this.
I am willing to collaborate.

Best regards,

Vlad

**Comment by marcstreeter** [comment]
Yo - any movement on this?  I'm not sure if these changes were ever merged in. I'm more than willing to do the 'bureaucratic things' if that's all that's needed to get these great additions into the library

**Comment by AidasK** [comment]
I have started refactoring this lib at develop branch https://github.com/flowjs/flow.js/tree/develop, it has the basic structure with well covered tests. Currently there is no html example/demo or any js documentation so far. It would be great to find a developer who would like to contribute.

**Comment by marcstreeter** [comment]
Quick question -- are any of the changes that vveladd implemented present in the development branch?  Much of the vars and functions he mentioned as added seem to be absent.

**Comment by vvllaadd** [comment]
As soon as I will get a bit of free time I will start a new public project based on my code. It has been successfully tested during one year with thousands of users and millions of uploads.
If I don't post anything here in a week or two, write a message to remind me about it ;)

**Comment by marcstreeter** [comment]
Awesome - I'll put it on my calendar.

**Comment by Patrik-Lundqvist** [comment]
Any updates on the new project @vvllaadd? :)

**Comment by vvllaadd** [comment]
@Patrik-Lundqvist , @marcstreeter anybody else interested, you can watch this project: https://github.com/vvllaadd/filerun , i still need to find some free time to start it up, but it will certainly happen durring February

**Comment by vvllaadd** [comment]
The project at the link above has been started and initial code is available for download, with an included example.

**Comment by jdc18** [comment]
Hi, 
I have an example with java, it works, but it still has some errors, https://github.com/jdc18/ng-flow-with-java/tree/master/ng-flow-java, i update the java - resumable example, if anybody wants to test it, it works with cors too.  This is my first project so any improvement on the code is welcomed.

**Comment by rohittk** [comment]
How does the joining of chunks work in the library, or is something that needs to be handled on the server side
