### ISSUE TITLE
programmatically pass parameter to flowjs target uri- uploading images to a webapi,

### ISSUE THREAD

**Issue by ysfkel** [flowjs/flow.js#57]
first of all, this might be a basic question. I am working with flowjs to upload files to a webapi i need to set id field on each upload.. it appears the target attribute cannot be edited from angularjs controller in my controller I tried this

```
$scope.uploadImages = function (flowObject, id)
{
  //  flowObject.defaults.target = "/api/apiimages/" + id;
  }
```

my api looks like this:

upload(int id){}
I have searched so much on the internet and couldnt get a solution to this, thanks

**Comment by yoyoprs** [comment]
In this case URL is static, only parameters are dynamic.

**Comment by larissaleite** [comment]
My URL is not working, it doesn't recognize the parameter. This is what I get:

http://localhost:5000/upload/function%20(FlowFile,%20FlowChunk,%20isTest)%2…turn%20'/api/file/upload/'+FlowFile.flowObj.id%20%20%20%20%20%20%7D
