### ISSUE TITLE
Expose a promise on file.cancel() to know when the ongoing request that we want to cancel is done

### ISSUE THREAD

**Issue by vionita** [flowjs/flow.js#62]
So here is what I need it for:

I cancel an upload:
              `file.cancel();`

But on the server side, I'm stuck now with a temp file. And I want to delete it.
             `$http.delete('/rest/upload/' + file.uniqueIdentifier);`

The thing is that the current chunk upload is not done yet when the temp file deletion comes by REST and I'm deleting a temp file that is currently in use by the upload.

So my workaround is to wait a little bit. But that's just awful.

``` javascript
file.cancel();
waitToCancel();
$http.delete('/rest/upload/' + file.uniqueIdentifier);
```

What I'll like to do is use a promise instead:

``` javascript
file.cancel().then(function(){
  $http.delete('/rest/upload/' + file.uniqueIdentifier);
});
```

**Comment by aayusharyan** [comment]
@vionita 
It's a reply after 5 years. 😅 However, I find that the specification is when you call the function, it will cancel the request immediately in that specific thread... So, calling $http.delete after cancel() will be fine.

**Comment by aayusharyan** [comment]
@AidasK 
Better to close for now. ?

**Comment by AidasK** [comment]
sure
