### ISSUE TITLE
Dot in directory (flow.js) breaks grunt plugins

### ISSUE THREAD

**Issue by genu** [flowjs/flow.js#73]
The issue is outlined in detail here: flowjs/ng-flow/issues/110

**Comment by AidasK** [comment]
My quick solution(`bower register flow-js https://github.com/flowjs/flow.js`):
```
 ~ $ bower install flow-js
bower flow-js#*                 cached git://github.com/flowjs/flow.js.git#2.8.0
bower flow-js#*               validate 2.8.0 against git://github.com/flowjs/flow.js.git#*
bower flow-js#~2.8.0           install flow-js#2.8.0
flow-js#2.8.0 bower_components/flow-js
```
![Bam](http://www.rmcbetter2gether.com/wp-content/uploads/2014/06/bam.jpeg)

This should solve your problem.

**Comment by genu** [comment]
Didn't know you could do that. So for ng-flow to reference this package `flow-js`, I'd need to follow the same idea and create another package, and set its dependency to `flow-js` rather than `flow.js`?

**Comment by AidasK** [comment]
No, just leave  `flow.js`  dependency for `ng-flow` library and require `flow-js` for your own package. Flow.js will be downloaded two times in separate directories.
