### ISSUE TITLE
Accessing blob object of added files

### ISSUE THREAD

**Issue by ImanMh** [flowjs/flow.js#78]
I want to have preview of my files before upload, is it possible to do something like this?

```javascript
f.on('fileAdded', function(file, event){
    var reader = new FileReader();
    reader.onload = function (e) {
      $('#preview').
          attr('src', e.target.result);
    }
    reader.readAsDataURL(file.blob);    
    f.upload();
  });
```

**Comment by leftis** [comment]
I am interested on functionality like this. Anyone got something?

**Comment by ImanMh** [comment]
I don't know how is this achieved on flow.js demo page, because when I add photos to gallery upload I immediately see the preview and then the upload begins.

**Comment by leftis** [comment]
@AidasK any ideas on how can we achieve showing a thumb of the temp file before uploading?

**Comment by AidasK** [comment]
Yes, you might want to copy logic from angularjs directive https://github.com/flowjs/ng-flow/blob/master/src/directives/img.js
You should update your ui on `filesSubmitted` event.

**Comment by leftis** [comment]
@AidasK thank you so much..!!! <3

**Comment by ImanMh** [comment]
Thanks!
I changed my code to this and it works:
```javascript
f.on('filesSubmitted', function(array, event){
    var reader = new FileReader();
    reader.readAsDataURL(array[0].file);    
    reader.onload = function (e) {
      $('#preview').
          attr('src', e.target.result);
    }
  });
```
And moved all my upload start logic into ```fileAdded``` event.
