### ISSUE TITLE
File upload only works once

### ISSUE THREAD

**Issue by ImanMh** [flowjs/flow.js#79]
I manually fail my uploads by returning a 404 header from my server to test retry feature of flowJS how ever I'm confused why flow.js only upload files once. Here is the screenshot of my network panel.

![screen shot 1393-11-16 at 11 57 28](https://cloud.githubusercontent.com/assets/4482199/6057060/ccbc352a-ad2e-11e4-84c3-847c5e1c81bd.png)

After first drag and drop upload starts and immediately fails but when I call upload method of my Flow object manually it wont start the upload again. As you see no network request is made. Even if drag and drop the same file the upload does not begin. It only starts if I give it a different file. Is there anything that I should reset before starting upload again?

**Comment by AidasK** [comment]
File has encountered a permanent error due to 404 error
https://github.com/flowjs/flow.js#configuration
Set `permanentErrors` to `[500]`, or you should reset file by calling
https://github.com/flowjs/flow.js#methods-1 `file.retry()`

**Comment by AidasK** [comment]
What is the point of retrying the upload if upload target does not exists?

**Comment by ImanMh** [comment]
As I said I'm trying to test my retry functionality. Anyway I changed my server side code and returned 403 instead of 404 which is not  one of permanentErrors by default. But again calling upload method of my flow object does not start uploading files even there are files in that object. Here is my console. 
```
//I see a 403  error here so manually trying to upload again
> tinyPic.upload();  
< undefined //nothing happens in my network panel
> tinyPic.files
< [e] //I see my file in tinyPic files array
> tinyPic.files[0].retry()
< undefined //nothing happens in my network panel
```

**Comment by ImanMh** [comment]
Oops, sorry sounds like calling tinyPic.files[0].retry() actually does upload the file again.
Thanks.

**Comment by AidasK** [comment]
You need to set `maxChunkRetries` to > 0.

**Comment by ImanMh** [comment]
Thanks @AidasK  ```maxChunkRetries``` seems to be an awesome feature but I'm also looking for a way that user retries the upload manually (by a click) which I've currently achieved by calling retry function of individual files.  ```maxChunkRetries``` does this automatically.

**Comment by jondkinney** [comment]
@ImanMh I just ran into this issue but in a slightly different setting. I wanted idempotent behavior for file upload, so if a user dragged the file on to the drop zone again, I wanted Flow.js to re-upload it. By default Flow.js won't upload a file that already exists in a Flow object's fileList (from what I can tell anyway), so to get around this you can store a global reference to your Flow object (`window.r = r;`), and then after a successful file upload (or file delete) call `window.r.cancel()` which will "Cancel upload of all FlowFile objects and remove them from the list." according to the docs for `.cancel()` here: https://github.com/flowjs/flow.js#methods

I also needed this for after deleting a file via ajax (Ruby on Rails), I couldn't immediately re-upload that file. So again, after delete I call out to my Flow object stashed on the window and `window.r.cancel()` and then I can re-upload a just delete file without needing to do a full page refresh to re-setup the Flow object's proper internal state. 

For my money this should be the default behavior, but whatever. At least after several weeks of messing with another developer's implementation of flow.js in our app, I was able to make it work the way I want.

**Comment by ImanMh** [comment]
@jondkinney Nice to hear you found a solution for your problem. Some parts of the library seems strange to me too but this is absolutely one of the best open source file uploaders.
