### ISSUE TITLE
dynamically changing target URL

### ISSUE THREAD

**Issue by nandhagam** [flowjs/flow.js#86]
Is it possible to dynamically change the target URL?

**Comment by xandeadx** [comment]
~~~
myflowobject.opts.target = 'new/url';
~~~

No?

**Comment by yoyoprs** [comment]
When you change the target or query parameter in the scope (or in the root scope).

All running uploads are affected and chunks are sent to the new target :(

I also tried to assign the url target every file via the flow-file-added event and impossible to fix the url on a single file ...

**Comment by dolymood** [comment]
target can be a string or a function.u can use a function to handle it.

**Comment by yoyoprs** [comment]
This does not change anything, it is the flow object that is affected and not the file object.
If an upload is in progress and we change the target parameter for another/next file, the upload is in progress at the next sending chunk will be sent to the new target parameter

**Comment by dolymood** [comment]
If the `target` is a function, we don't need to change it. As you said, we can assign the url target every file.So we just need to return it in the `target` function.

```js
var target = 'base target'
var flow = new Flow({
  target: function(fileObj) {
    return fileObj.targetUrl;
  }
});

flow.on('fileAdded', function(fileObj) {
  fileObj.targetUrl = target + '...'
});
```

Maybe my idea was wrong. O(∩_∩)O

**Comment by yoyoprs** [comment]
Target is an attribute of the flow object and purpose is not to create a new flow to each upload. It is necessary that the file object has its own target attribute.

**Comment by erictvalverde** [comment]
+1

**Comment by evilaliv3** [comment]
we are ok for the proposal of @dolymood.

it would great if some of you could go for it's implementation and for the implementation of a unit test for it; this would speed up the addition of that more than a +1 :)

**Comment by aayusharyan** [comment]
Since this thread is old and there is no recent progress. I'm closing this.
Also, the point requested initially can be fixed if we pass a function to `target` in the defaults.
Feel free to re-open.
