### ISSUE TITLE
send data blob without headers

### ISSUE THREAD

**Issue by DmitryEfimenko** [flowjs/flow.js#87]
Hello, first thing is first - awesome library!
I use it in all my projects. However, in the latest project I have a very weak back end, and any sort of chunk processing slows down the whole thing tremendously.
Thus I'm wondering if there is a way to configure flowJs to send data without the headers.
The example below shows what server gets when uploading a small json file:
```
------WebKitFormBoundaryxUrql8xW7BtWpE14
Content-Disposition: form-data; name="flowChunkNumber"

1
------WebKitFormBoundaryxUrql8xW7BtWpE14
Content-Disposition: form-data; name="flowChunkSize"

1048576
------WebKitFormBoundaryxUrql8xW7BtWpE14
Content-Disposition: form-data; name="flowCurrentChunkSize"

13
------WebKitFormBoundaryxUrql8xW7BtWpE14
Content-Disposition: form-data; name="flowTotalSize"

13
------WebKitFormBoundaryxUrql8xW7BtWpE14
Content-Disposition: form-data; name="flowIdentifier"

13-WhiteBoardPointjson
------WebKitFormBoundaryxUrql8xW7BtWpE14
Content-Disposition: form-data; name="flowFilename"

WhiteBoardPoint.json
------WebKitFormBoundaryxUrql8xW7BtWpE14
Content-Disposition: form-data; name="flowRelativePath"

WhiteBoardPoint.json
------WebKitFormBoundaryxUrql8xW7BtWpE14
Content-Disposition: form-data; name="flowTotalChunks"

1
------WebKitFormBoundaryxUrql8xW7BtWpE14
Content-Disposition: form-data; name="file"; filename="blob"
Content-Type: application/octet-stream

{"X":0,"Y":0}
------WebKitFormBoundaryxUrql8xW7BtWpE14--

```
What I'd like is to be able to only send the actual data (in this case: `{"X":0,"Y":0}`) without any flowjs headers.
Any help is appreciated!

**Comment by AidasK** [comment]
Hi, glad to hear :).

Try setting `method` config parameter to `octet`. All parameters will be passed to url query and your data will be in the body.

**Comment by DmitryEfimenko** [comment]
totally worked! Thanks!
