### ISSUE TITLE
Preprocess

### ISSUE THREAD

**Issue by vvllaadd** [flowjs/flow.js#9]
Could anyone please explain the purpose of the "preprocess" custom function? I fail to see a case where it might be useful.

**Comment by hellais** [comment]
I would like to point out the use case for which I plan to use the preprocess function.

My goal is to implement end to end encrypted streaming file uploads. For this reason I need to encrypt every chunk before it is sent to the wire.

I plan to implement this by mocking the FileAPI interface for accessing a file, mainly by implementing the `slice` method to return a Blob I have constructed client side.

I believe the preprocess method could be improved by allowing the user to also return a the content of the chunk to be uploaded and would make implementing something similar to this much easier.

Other use cases I see possible include streaming a file by doing client side compression/encoding or any other transformation on the data (without having to store the whole file in memory) before it is sent to the server.

So I guess I have two questions for you:

1) Do you believe the approach I have described above is reasonable?
2) Would you be interested in having an implementation of the better solution I described be part of flow.js?

**Comment by vvllaadd** [comment]
How about just transferring the data over SSL/HTTPS instead of adding some custom encryption system which you might get wrong?
As for the compression, I can't remember any file type which is not using any compression by default.
Even calculating checksums is completely redundant action.
There is no need whatsoever for chunk preprocessing.

**Comment by hellais** [comment]
@vvllaadd we are not using a custom encryption scheme, we are using PGP, in particular the openpgpjs implementation of it: https://github.com/openpgpjs/openpgpjs that has received security audits: https://github.com/openpgpjs/openpgpjs/wiki/Cure53-security-audit and is used in a variety of different pieces of software.

I will not go into the numerous reasons why this is not the same thing as using HTTPS (TLS).

Anyways wether or not the goal is a good idea is out of scope, what I am asking is if implementing the solution in this way is good or not.

**Comment by evilaliv3** [comment]
@vvllaadd our need for PGP on the GlobaLeaks project is different from what SSL/HTTPS is thought for.
What we are trying to develop is end2end encryption from a sender to a receiver where the server need to receive a payload already encrypted and not readable by the server owner itself.

I think that the library may benefit of such a hook possibility given the possible extension that one can build on them and the library itself can probably use it for debugging pourpuses.

**Comment by vvllaadd** [comment]
Watch this project https://github.com/vvllaadd/filerun.js, I will add the base code today or tomorrow and will consider adding the hook in a future version.

**Comment by tcurtil** [comment]
This is a really old request, but it is possible with current flow version (2.11.2) to achieve it using this configuration :

    var r = new Flow({
	    target:...,
        chunkSize: ...,
        simultaneousUploads: ...,
        forceChunkSize: ...,
	    maxChunkRetries: ...,
	    preprocess : function(chunk) {
	    	if (chunk.readState == 0) {
	    		// readState=0 : read of file chunk not started. Triggering it now.
	    		chunk.preprocessState = 0;
	    		var read = chunk.flowObj.opts.readFileFn;
	    		read(chunk.fileObj, chunk.startByte, chunk.endByte, chunk.fileObj.file.type, chunk);
	    	} else if (chunk.readState == 1) {
	    		// waiting... readState=1 : read of chunk is in progress. 
	    		chunk.preprocessState = -1;
	    	} else if (chunk.readState == 2) {
	    		// readState=2 : read is finished. We can trigger now MD5 compute.
	    		var reader = new FileReader();
	    		reader.onloadend = function () {
	    		    chunk.md5sum = SparkMD5.ArrayBuffer.hash(reader.result);
	    		    console.log('Finished computing chunk#' + chunk.offset + '(starting at : ' + chunk.startByte +
	    				        ', finishing at : ' + chunk.endByte + ')' + ' md5 : ' + chunk.md5sum);
		    	    chunk.preprocessFinished();
				};
	    		reader.readAsArrayBuffer(chunk.bytes);
	    	}
	    },
	    query : function(file, chunk, isTest) {
	    	return {'md5sum' : chunk.md5sum};
	    }
	});

It is using SparkMD5, but any other lib should be working too, just replace the line `chunk.md5sum = SparkMD5.ArrayBuffer.hash(reader.result);` with your lib.
