### ISSUE TITLE
Is there a way to upload small files without chunking?

### ISSUE THREAD

**Issue by canebat** [flowjs/flow.js#95]
I have small files that I want to upload that are roughly 5MB or less. Is there a way I can upload the files without chunking?

**Comment by canebat** [comment]
Well, missed the `chunkSize` part. I set that to 5MB and it worked.

**Comment by canebat** [comment]
Actually, is there an option to upload files without chunking at all? ie, an option like `chunking: false`?

**Comment by AidasK** [comment]
Set it to infinity
chunkSize: Number.MAX_VALUE

**Comment by AidasK** [comment]
And `testChunks: false`
