### ISSUE TITLE
Flow.js is missing the configuration possibility to limit the maximum filesize limit for uploads.

### ISSUE THREAD

**Issue by evilaliv3** [flowjs/flow.js#96]
Flow.js is missing the configuration possibility to limit the maximum file-size limit for uploads.

I would be important to implement a  configuration variable in order to block file uploads over a certain file-size; the same should be probably evaluated in order to define an allowed extension list.

**Comment by evilaliv3** [comment]
maybe that the lack of this feautures is intentional in order to keep the library small and rely on user functions implemented by means of ".fileAdded(file, event)" event; i'm ok with that but probably it would be good to add some examples and documentation for the benefit of other users implementations.

**Comment by evilaliv3** [comment]
@AidasK we implemented the fileAdded event callback returning false as specified when the uopload should be rejected.

by the way this seems to not work at all. could you please investigate the issue?

here you find our implementation code: https://github.com/globaleaks/GlobaLeaks/commit/8bf077ef79ea3de19e66b6c7cdb1700f09133e9c

**Comment by evilaliv3** [comment]
@AidasK i've solved my issue calling the event.preventDefault() function.

maybe the documentation is outdated in relation to this?

**Comment by AidasK** [comment]
fileAdded must be used for custom validation. I have added a comment on the commit how to solve it. Hope it works ;)

**Comment by AidasK** [comment]
This is not an issue, ngFlow just works different. You can open a pull request if you find an outdated docs, thanks.
