### ISSUE TITLE
generateUniqueIdentifier invked two times

### ISSUE THREAD

**Issue by mcianc** [flowjs/flow.js#99]
Using custom generateUniqueIdentifier my function is invoked two times for each added files

```
            $scope.MyFlow = new Flow({
                target: api + "/Api/FileCommit",
                //testMethod : "POST",
                testChunks: false,
                uploadMethod: "POST",
                generateUniqueIdentifier: function (file) {

                    var uuid = 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, function (c) {
                        var r = Math.random() * 16 | 0, v = c == 'x' ? r : (r & 0x3 | 0x8);
                        return v.toString(16);
                    });

                    console.log(file.size + "." + uuid)
                    return file.size + "." + uuid;

                }

            });
```

This is not a really issue but, should be fixed is some release.

**Comment by nicolaspayot** [comment]
I'd like to fix this "issue" but a bunch of unit tests fail on the master branch. What can I do?

**Comment by jabyrd3** [comment]
Can anybody help me out with this? I'm stuck and if I can't get this working I'm not going to be able to use flow.

@nicolaspayot what did you do to get this working?

**Comment by jabyrd3** [comment]
An interesting thing I am noticing is that it only does this for the first file upload through the ng-flow directives. Subsequent uploads don't file another generateUniqueIdentifier call.

**Comment by AidasK** [comment]
https://github.com/flowjs/flow.js/pull/218
